env:
  global:
    - allure_results_dir=./allure_results
    - allure_report_dir=./allure_report
language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - chmod +x run_test.sh
  - ./run_test.sh || echo "done"

before_deploy:
  - sleep 5
  - ls
  - echo "done"
deploy:
#  local_dir: $allure_report_dir
  local_dir: ./allure_report
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master