language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install allure-pytest
#  - pip install -r requirements.txt

# command to run tests
script:
  - export allure_results_dir=./allure_results
  - export allure_report_dir=./allure_report
  - rm -rf $allure_results_dir
  - rm -rf allure_report_dir
  - pytest --alluredir=$allure_results_dir
  - allure generate --clean --report-dir=$allure_report_dir $allure_results_dir